### ISSUE TITLE
Plugin always throws Critical Error

### ISSUE THREAD

**Issue by ChrisColotti** [jl455/woocommerce-cardconnect#5]
I have tried everything, posted in the plugin forums, and contacted CardConnect support.  Nobody is helping with this.

Debug logging shows nothing, I've tried on 3 different servers.  I'm using my live ID correct password and "fts" in the site but it constantly throws these errors:

"Payment error: A critical server error prevented this transaction from completing. Please confirm your information and try again."

"CardConnect failed transaction. Response: CURL error?"

There is multiple reports of these errors on the plugin forum from back to MARCH with no updates.  

Wordpress version:  4.9.7
Plugin Version 2.0.17
WooCommerce version 3.4.3

Clearly something is broken with this plugin and it's not allowing me to use my preferred payment processing of CardConnect and I am forced to use PayPal and Pay more in fees!

**Comment by 8bit-echo** [comment]
@ChrisColotti did you find resolution on this issue? Most of the googling I've done on this error leads to some post by you.

**Comment by ChrisColotti** [comment]
It has been working now for a while.  Thinking back I believe it was something with the hosting provider and I’ve since switched providers.  I’ve not had this error now for some time.  Also this may have been an issue with using the incorrect credentials.  The docs were not clear on that you must obtain specific credentials to use the plugin not your normal website ones.

**Comment by RexAK** [comment]
@8bit-echo The version you are using (2.0.17) is extremely outdated, and this particular Github repo for the plugin has been dead-ended in favor of using the WordPress SVN for tracking and updates.

Please download the newest version (v3+) from the Wordpress plugin repo: 
https://downloads.wordpress.org/plugin/cardconnect-payment-module.3.1.3.zip

Closing this...

**Comment by 8bit-echo** [comment]
@RexAK Thanks for the info. I'm using the most up to date version of the plugin, but it's throwing the same error as what Christ was seeing. I was able to resolve my issue by getting the Merchant ID, username and password reset by CardConnect. Everything is working as expected now.
